[2025-08-11T02:18:30.727+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: public_health_data_pipeline.load_clean_data_to_postgres manual__2025-08-11T02:18:28.046433+00:00 [queued]>
[2025-08-11T02:18:30.730+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: public_health_data_pipeline.load_clean_data_to_postgres manual__2025-08-11T02:18:28.046433+00:00 [queued]>
[2025-08-11T02:18:30.730+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-11T02:18:30.734+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_clean_data_to_postgres> on 2025-08-11 02:18:28.046433+00:00
[2025-08-11T02:18:30.736+0000] {standard_task_runner.py:60} INFO - Started process 186 to run task
[2025-08-11T02:18:30.737+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'public_health_data_pipeline', 'load_clean_data_to_postgres', 'manual__2025-08-11T02:18:28.046433+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/covid_data_pipeline.py', '--cfg-path', '/tmp/tmplq2ydy2n']
[2025-08-11T02:18:30.738+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask load_clean_data_to_postgres
[2025-08-11T02:18:30.755+0000] {task_command.py:423} INFO - Running <TaskInstance: public_health_data_pipeline.load_clean_data_to_postgres manual__2025-08-11T02:18:28.046433+00:00 [running]> on host 833c0b0d1c2f
[2025-08-11T02:18:30.855+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='public_health_data_pipeline' AIRFLOW_CTX_TASK_ID='load_clean_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T02:18:28.046433+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-11T02:18:28.046433+00:00'
[2025-08-11T02:18:30.856+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-08-11T02:18:30.856+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-08-11T02:18:30.864+0000] {sql.py:450} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS covid_state_metrics (
                date DATE,
                state VARCHAR(50),
                fips INTEGER,
                cases INTEGER,
                deaths INTEGER,
                new_cases INTEGER,
                new_deaths INTEGER,
                PRIMARY KEY (date, state)
            );
        , parameters: None
[2025-08-11T02:18:30.865+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-08-11T02:18:30.868+0000] {sql.py:450} INFO - Running statement: TRUNCATE TABLE covid_state_metrics;, parameters: None
[2025-08-11T02:18:30.872+0000] {postgres.py:172} INFO - Running copy expert: COPY covid_state_metrics FROM STDIN WITH CSV HEADER, filename: <_io.StringIO object at 0xffff863988b0>
[2025-08-11T02:18:30.872+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/covid_data_pipeline.py", line 97, in load_clean_data_to_postgres
    pg_hook.copy_expert(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/hooks/postgres.py", line 173, in copy_expert
    if not os.path.isfile(filename):
  File "/usr/local/lib/python3.9/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not StringIO
[2025-08-11T02:18:30.876+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=public_health_data_pipeline, task_id=load_clean_data_to_postgres, execution_date=20250811T021828, start_date=20250811T021830, end_date=20250811T021830
[2025-08-11T02:18:30.880+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 26 for task load_clean_data_to_postgres (stat: path should be string, bytes, os.PathLike or integer, not StringIO; 186)
[2025-08-11T02:18:30.921+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-11T02:18:30.929+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
