[2025-08-11T02:10:38.272+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: public_health_data_pipeline.create_postgres_table_if_not_exists manual__2025-08-11T02:10:36.814083+00:00 [queued]>
[2025-08-11T02:10:38.276+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: public_health_data_pipeline.create_postgres_table_if_not_exists manual__2025-08-11T02:10:36.814083+00:00 [queued]>
[2025-08-11T02:10:38.276+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-11T02:10:38.280+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): create_postgres_table_if_not_exists> on 2025-08-11 02:10:36.814083+00:00
[2025-08-11T02:10:38.283+0000] {standard_task_runner.py:60} INFO - Started process 174 to run task
[2025-08-11T02:10:38.285+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'public_health_data_pipeline', 'create_postgres_table_if_not_exists', 'manual__2025-08-11T02:10:36.814083+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/covid_data_pipeline.py', '--cfg-path', '/tmp/tmpqph3xnsu']
[2025-08-11T02:10:38.286+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask create_postgres_table_if_not_exists
[2025-08-11T02:10:38.324+0000] {task_command.py:423} INFO - Running <TaskInstance: public_health_data_pipeline.create_postgres_table_if_not_exists manual__2025-08-11T02:10:36.814083+00:00 [running]> on host c5cd2a866581
[2025-08-11T02:10:38.360+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='public_health_data_pipeline' AIRFLOW_CTX_TASK_ID='create_postgres_table_if_not_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T02:10:36.814083+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-11T02:10:36.814083+00:00'
[2025-08-11T02:10:38.365+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-08-11T02:10:38.376+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/covid_data_pipeline.py", line 45, in create_postgres_table_if_not_exists
    pg_hook.run(create_table_sql)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known

[2025-08-11T02:10:38.381+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=public_health_data_pipeline, task_id=create_postgres_table_if_not_exists, execution_date=20250811T021036, start_date=20250811T021038, end_date=20250811T021038
[2025-08-11T02:10:38.388+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task create_postgres_table_if_not_exists (could not translate host name "postgres" to address: Name or service not known
; 174)
[2025-08-11T02:10:38.423+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-11T02:10:38.434+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
