[2025-08-11T20:50:14.138+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: public_health_data_pipeline.stage_raw_data_to_s3 manual__2025-08-11T20:50:10.970479+00:00 [queued]>
[2025-08-11T20:50:14.141+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: public_health_data_pipeline.stage_raw_data_to_s3 manual__2025-08-11T20:50:10.970479+00:00 [queued]>
[2025-08-11T20:50:14.141+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-11T20:50:14.149+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): stage_raw_data_to_s3> on 2025-08-11 20:50:10.970479+00:00
[2025-08-11T20:50:14.152+0000] {standard_task_runner.py:60} INFO - Started process 186 to run task
[2025-08-11T20:50:14.154+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'public_health_data_pipeline', 'stage_raw_data_to_s3', 'manual__2025-08-11T20:50:10.970479+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/covid_data_pipeline.py', '--cfg-path', '/tmp/tmpwtsyvpxo']
[2025-08-11T20:50:14.155+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask stage_raw_data_to_s3
[2025-08-11T20:50:14.162+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-11T20:50:14.177+0000] {task_command.py:423} INFO - Running <TaskInstance: public_health_data_pipeline.stage_raw_data_to_s3 manual__2025-08-11T20:50:10.970479+00:00 [running]> on host 6e6820ad3c70
[2025-08-11T20:50:14.287+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='public_health_data_pipeline' AIRFLOW_CTX_TASK_ID='stage_raw_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T20:50:10.970479+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-11T20:50:10.970479+00:00'
[2025-08-11T20:50:14.293+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-11T20:50:14.413+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-08-11T20:50:15.219+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-11T20:50:15.227+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=public_health_data_pipeline, task_id=stage_raw_data_to_s3, execution_date=20250811T205010, start_date=20250811T205014, end_date=20250811T205015
[2025-08-11T20:50:15.276+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-11T20:50:15.286+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
